apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-upgrade

resources:
- https://github.com/rancher/system-upgrade-controller/releases/download/v0.19.0/crd.yaml
- https://github.com/rancher/system-upgrade-controller/releases/download/v0.19.0/system-upgrade-controller.yaml
- server-plan.yaml

patches:
- target:
    group: upgrade.cattle.io
    kind: Plan
    name: server-plan
    version: v1
  patch: |-
    - op: replace
      path: /spec/version
      # renovate: datasource=docker depName=rancher/k3s-upgrade versioning=docker
      value: v1.35.1-k3s1
