apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-home-dot
  namespace: adguard-home
  labels:
    app: adguard-home
spec:
  ingressClassName: tailscale
  rules:
    - host: adguard-home-dot
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adguard-home-dns
                port:
                  number: 853
  tls:
    - hosts:
        - adguard-home-dot
